[workspace]
members = [
]

[package]
name = "asmgen"
authors = ["C2Rust", "Tyler Port"]
version = "0.0.0"
publish = false
edition = '2021'


[[bin]]
path = "src/compiler.rs"
name = "compiler"

[dependencies]
# libc = "0.2"



