# [build]
# rustflags = "-C target-feature=-avx2,-avx,+crt-static"

# [target.x86_64-unknown-linux-gnu]                                                                   
# linker = "/home/tport/libcpuidoverride/libcpuidoverride.so" 

# [rust]
# lld = true